import "./globals.css";
import { Inter } from "next/font/google";
import ContextProvider from "@/context/ContextProvider.jsx";
import MyRoot from "@/app/MyRoot.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <MyRoot> {children}</MyRoot>
        </ContextProvider>
      </body>
    </html>
  );
}
